version: '2'
services:
    segurancatrabalho-app:
        image: segurancatrabalho
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://segurancatrabalho-postgresql:5432/segurancatrabalho
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    segurancatrabalho-postgresql:
        extends:
            file: postgresql.yml
            service: segurancatrabalho-postgresql
